# Generated by Django 5.2.6 on 2025-09-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=225)),
                ('doc_spec', models.CharField(max_length=255)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.departments')),
            ],
        ),
    ]
