# Generated by Django 5.2.6 on 2025-09-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0002_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
