# Generated by Django 5.2.6 on 2025-09-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='avail_days',
            field=models.CharField(default='Monday', max_length=100),
        ),
    ]
