# Generated by Django 5.2.6 on 2025-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0005_doctors_avail_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
            ],
        ),
    ]
