# Generated by Django 5.2.6 on 2025-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0006_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
