# Generated by Django 5.2.6 on 2025-09-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0008_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.booking'),
        ),
    ]
