# Generated by Django 5.2.6 on 2025-09-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0009_alter_status_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='p_id',
        ),
    ]
