# Generated by Django 5.2.6 on 2025-09-30 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0010_remove_status_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
