# Generated by Django 5.2.7 on 2025-10-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0012_status_status_status_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='System.booking'),
        ),
    ]
