# Generated by Django 5.2.7 on 2025-10-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0014_alter_booking_p_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='status',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System.booking'),
        ),
    ]
