# Generated by Django 5.2.7 on 2025-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0015_remove_status_status_remove_status_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
