# Generated by Django 5.2.7 on 2025-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0016_alter_booking_p_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_phone',
            field=models.CharField(max_length=50),
        ),
    ]
