# Generated by Django 5.2.7 on 2025-10-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0018_alter_booking_p_email_alter_booking_p_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
