# Generated by Django 5.2.7 on 2025-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0019_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
