# Generated by Django 5.2.7 on 2025-10-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0020_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
