# Generated by Django 5.2.7 on 2025-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System', '0021_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
